<?php

namespace RKW\RkwMailer\Cache;

/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
*/

use TYPO3\CMS\Core\Cache\CacheManager;
use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Database\Query\Restriction\BackendWorkspaceRestriction;
use TYPO3\CMS\Core\Database\Query\Restriction\DeletedRestriction;
use TYPO3\CMS\Core\Log\LogLevel;
use TYPO3\CMS\Core\Log\LogManager;
use TYPO3\CMS\Core\Utility\GeneralUtility;

/**
 * AbstractCache
 *
 * @author Steffen Kroggel <developer@steffenkroggel.de>
 * @copyright Rkw Kompetenzzentrum
 * @package RKW_RkwMailer
 * @license http://www.gnu.org/licenses/gpl.html GNU General Public License, version 3 or later
 */
abstract class AbstractCache
{


    /**
     * Cache
     *
     * @var \TYPO3\CMS\Core\Cache\Frontend\VariableFrontend
     */
    protected $cache;


    /**
     * Logger
     *
     * @var \TYPO3\CMS\Core\Log\Logger
     */
    protected $logger;


    /**
     * Constructor
     * @throws \RKW\RkwMailer\Exception
     */
    public function __construct()
    {
        $this->cache = GeneralUtility::makeInstance(CacheManager::class)->getCache('rkw_mailer');
        $this->logger = GeneralUtility::makeInstance(LogManager::class)->getLogger(__CLASS__);
        $this->securityCheck();
    }


    /**
     * Gets the cache object
     * @return \TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
     */
    public function getCache(): \TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    {
        return $this->cache;
    }
    

    /**
     * Returns cached content
     *
     * @param string $cacheIdentifier
     * @return string
     */
    public function getContent(string $cacheIdentifier): string
    {

        if ($this->cache->has($cacheIdentifier)) {

            // get cached content
            $this->logger->log(
                LogLevel::DEBUG,
                sprintf(
                    'Getting cache for identifier "%s".',
                    $cacheIdentifier
                )
            );
            return $this->cache->get($cacheIdentifier);
        }

        return '';
    }

    
    /**
     * Sets cache content
     *
     * @param string $cacheIdentifier
     * @param mixed $value
     * @return void
     */
    public function setContent(string $cacheIdentifier, $value): void
    {

        $this->logger->log(
            LogLevel::DEBUG,
            sprintf(
                'Setting cache for identifier "%s".',
                $cacheIdentifier
            )
        );
        
        $className = strtolower(substr(strrchr(get_class($this), '\\'), 1));
        $this->cache->set(
            $cacheIdentifier,
            $value,
            array(
                'tx_rkwmailer_' . $className,
            ),
            86400
        );
    }

    
    /**
     * Clear cached content
     */
    public function clearCache(): void
    {
        $this->logger->log(LogLevel::DEBUG, 'Flushing cache');
        $this->cache->flush();
    }

    
    /**
     * .htaccess-based protection for SimpleFileBackend-Cache
     *
     * @return bool
     * @throws \RKW\RkwMailer\Exception
     */
    public function securityCheck(): bool
    {

        if (
            ($cacheBackend = $this->cache->getBackend())
            && ($cacheBackend instanceof \TYPO3\CMS\Core\Cache\Backend\SimpleFileBackend)
        ){
            
            $pathToApacheFile =  $cacheBackend->getCacheDirectory() . '.htaccess';
            $pathToNginxFile =  $cacheBackend->getCacheDirectory() . 'conf.nginx';

            // create .htaccess if there is none!
            if (! file_exists($pathToApacheFile)) {
                
                $content = '# This file is automatically generated.' . "\n" .
                    '# Please to not modify it manually because all changes may be lost.' . "\n\n" .
                    
                    '# Apache < 2.3' . "\n" .
                    '<IfModule !mod_authz_core.c>'. "\n" .
                    'Order allow,deny'. "\n" .
                    'Deny from all'. "\n" .
                    'Satisfy All'. "\n" .
                    '</IfModule>'. "\n\n" .
                    
                    '# Apache ≥ 2.3' . "\n" .
                    '<IfModule mod_authz_core.c>'. "\n" .
                    'Require all denied' . "\n" .
                    '</IfModule>';
                if (! file_put_contents($pathToApacheFile, $content)) {
                    throw new \RKW\RkwMailer\Exception('Cache directory is not secure and file for directory protection can not be written. Please fix this first');
                }
            }

            // create .htaccess if there is none!
            if (! file_exists($pathToNginxFile)) {

                $content = '# This file is automatically generated.' . "\n" .
                    '# Please to not modify it manually because all changes may be lost.' . "\n\n" .
                    'deny all;' . "\n" .
                    'satisfy all;';

                if (! file_put_contents($pathToNginxFile, $content)) {
                    throw new \RKW\RkwMailer\Exception('Cache directory is not secure and file for directory protection can not be written. Please fix this first');
                }
            }            
            
            return true;
        }

        return false;
    }

}